import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Tech Fleets',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div>
          <header className='p-8 border-b flex items-center justify-between bg-blue-500 rounded-br-lg rounded-bl-lg w-8/12 mx-auto mb-4'>
            <Link
              href={'/'}
              className='text-white font-sans font-bold text-3xl'
            >
              TECH FLEETS
            </Link>
            <Link
              href={'/create'}
              className='py-2 px-4 bg-white rounded-xl font-sans font-medium shadow-lg'
            >
              Add Fleet➕
            </Link>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
